### PR TITLE
Dave

### PR DESCRIPTION
**Pull request by Producks**
# Changelogs
⚠️ **Lot of changes have been made. Make sure you make nuke and make env before merging**⚠️     
⚠️ **Make sure to test most features, there was a lot of merge conflicts**⚠️  
# Backend
#### Interactive socket
* Added interactive socket, it will be created when a user log in and closed when a user leave or logout.
* It's responsible for notifications, invites and matching people together.
* The interactive socket support matchmaking.
* The notification part of the interactive socket is still work in progress.
#### Pong socket
* Added a pong socket, it will be created when a match is initiated and closed when the match is over.
* It's responsible for handling the connection between both players that are playing the game.
* Everything related to that should be final for now.
#### Chat socket
* Has been fully removed and nuke from existence.
#### Socket miscellaneous
* Django channel layer is no longer using postgres-channel, due to bottleneck issue.
* Django channel layer is now using the in memory storage for now. Will add [redis](https://redis.io/) if I have the time.
### Passwords
* Passwords are now hashed with PBKDF2.
* Increased password capacity to 128 in the database to have enough to store the hash.
* These are the methods available to use for making and checking passwords:
```python
password=make_password("input password") # Will generate an hash
check_password("input password", "hashed password in db") # Will return True if they match
```
### Settings
* Temporary added [*] for hosts for development, it will be restored later.
* Remove all instance of csrf checkup.

# Frontend
### Sockets
* Added a Socket class for the interactive token.
* Come with multiples methods that consist of initialization, communication and closing.
* Still work in progress until further info is given.

# Miscellaneous
* Updated make env to now add your hostname in the list of allowed host.

# Test results

### CODE REVIEW

**Comment by Jalevesq** [comment]
J'ai rencontré une erreur lors de la tentative de création d'un compte sur la page d'inscription. Cette erreur est survenue après avoir essayé de me connecter avec des comptes utilisateurs prédéfinis (users seeds) dans la base de données, ainsi qu'avec des comptes utilisateurs qui n'existent pas.

Par contre, quand je crée uncompte sans tenter me log, j'ai l'impression que ça marche sans problème.
Screenshot 2023-12-14 at 9 02 45 PM

**Comment by Jalevesq** [comment]
Uploading Screen Recording 2023-12-14 at 9.06.03 PM.mov…

**Review by Jalevesq — APPROVED** [review]
Tout fonctionne de mon côté. Clean!

**Review by KayzaFlo — APPROVED** [review]
👍

**Pull request merged**
