### PR TITLE
Addition of 2FA + patch settings

### PR DESCRIPTION
**Pull request by Jalevesq**
### Added
- Implemented Two-Factor Authentication (2FA) for enhanced security.
- Refined the structure of the settings file for better organization and readability.

### Improved
- Comprehensive error handling for login/signup and settings to ensure smoother user experience and reliability.

### CODE REVIEW

**Comment by Jalevesq** [comment]
⚠️ Accepter la PR de Dave avant celle ci ⚠️
Je vais merge dans ma branche après.

**Comment by Jalevesq** [comment]
Ready to be evaluated

**Review by KayzaFlo — APPROVED** [review]
👍

**Review by Producks — APPROVED** [review]

**Pull request merged**
