### PR TITLE
Jacob

### PR DESCRIPTION
**Pull request by Jalevesq**
# Changelog

### Added
- Added functionality to change the nickname in user settings. (Future enhancements will include password verification and the ability to change email/password.)
- Introduced a feature to upload a user avatar, along with a default avatar option.

### Changed
- Transformed the login/signup div into a form to utilize Bootstrap utilities for fields instead of JavaScript alerts.
- Updated tests to work with the avatar feature.

### Removed
- Removed the avatar field from the signup process.
- Eliminated one test from user_profile that was incompatible with the new requirement for a token for PATCH requests

### CODE REVIEW

**Review by xApologize — CHANGES_REQUESTED** [review]
Good work.

There is a popup when trying to login with the demo users. moving the demo users button outside of the <form> fix the issue.

changing username of demo user will make it so you cant connect with it anymore.

**Comment by Jalevesq** [comment]
> Good work.
> 
> There is a popup when trying to login with the demo users. moving the demo users button outside of the
> 
> fix the issue.
> changing username of demo user will make it so you cant connect with it anymore.

patch

**Review by xApologize — APPROVED** [review]
good! beau travail

**Review by Producks — APPROVED** [review]
[Good work!](https://www.twitch.tv/esskayuwu)

**Pull request merged**
